nps/urls.py
from allauth.account.views import LoginView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from accounts.views import login_after_password_change, privileges_required
from nps.views import login_success

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/password/change/', login_after_password_change, name='account_change_password'),
    path('privileges_required/', privileges_required, name="privileges_required"),
    path('accounts/', include('allauth.urls')),
    path('', include('dashboard.urls')),
    path('', include('products.urls')),
    path('', include('purchases.urls')),
    # path('', include('tanks.urls')),
    # path('', include('vehicles.urls')),
    path('', include('meters.urls')),
    path('', include('rent_received.urls')),
    path('', include('chart_of_accounts.urls')),
    path('', include('tank_lorries.urls')),
    path('', include('duties.urls')),
    path('', include('sales.urls')),
    path('', include('cash.urls')),
    path('', include('reports.urls')),
    # path('', include('customers.urls')),
    path('', include('expenses.urls')),
    path('', include('taxes.urls')),
    path('', include('discounts.urls')),
    path('', include('customer_limits.urls')),
    path('', include('bank_to_bank_transfer.urls')),
    path('', include('drawing.urls')),
    path('', include('bank_expense.urls')),
    path('', include('milli_short_recovery.urls')),
    path('', include('lorry_stock.urls')),
    path('login_success/', login_success, name='login_success'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent_received/urls.py
from django.urls import path
from .views import rent_received_list, rent_received_create, rent_received_update, rent_received_delete, rent_received_home

urlpatterns = [
    path('rent_received/', rent_received_list, name='rent_received_list'),
    path('rent_received/home', rent_received_home, name='rent_received_home'),
    path('rent_received/create', rent_received_create, name='rent_received_create'),
    path('rent_received/<int:pk>/update', rent_received_update, name='rent_received_update'),
    path('rent_received/<int:pk>/delete', rent_received_delete, name='rent_received_delete'),
]

rent_received/models.py
from django.db import models
from chart_of_accounts.models import ChartOfAccount
from duties.models import Duty
from nps.models import ModelWithTimeStamp


class Rentreceived(ModelWithTimeStamp):
    MONTHS = (
        ('', "Select a month"),
        (1, "January"),
        (2, "February"),
        (3, "March"),
        (4, "April"),
        (5, "May"),
        (6, "June"),
        (7, "Jully"),
        (8, "August"),
        (9, "September"),
        (10, "October"),
        (11, "November"),
        (12, "December")
    )
    STATUS = (
        (1, 'not posted'),
        (2, 'posted')
    )
    duty = models.ForeignKey(Duty, on_delete=models.CASCADE, null=True, blank=True, default=None, verbose_name='Duty',
                             db_index=True)
    bank = models.ForeignKey(ChartOfAccount, on_delete=models.CASCADE, null=True)
    rent_cheque_no = models.CharField(max_length=20, verbose_name='Cheques no')
    rent_receiving_date = models.DateTimeField(null=False, blank=False, verbose_name='Receiving date')
    rent_receiving_month = models.SmallIntegerField(choices=MONTHS, blank=False, verbose_name=' Rent receiving month')
    rent_bank_deposition_date = models.DateTimeField(null=False, blank=False, verbose_name='Bank deposition date')
    rent_amount = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='Rent amount')
    status = models.SmallIntegerField(verbose_name='', choices=STATUS, default=1, null=True, blank=True)
    class Meta:
        permissions = (('list_rentreceived', 'Can list rentreceived'),)

rent_received/forms.py
from django import forms
from django.forms import HiddenInput

from duties.models import Duty
from .models import Rentreceived
from chart_of_accounts.models import ChartOfAccount


def get_latest_duty_date():
    ld = Duty.objects.latest('id')
    return ld


class RentreceivedForm(forms.ModelForm):
    class Meta:
        model = Rentreceived
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(RentreceivedForm, self).__init__(*args, **kwargs)
        duty = get_latest_duty_date()
        self.fields['bank'].empty_label = 'Select a bank'
        self.fields['bank'].queryset = ChartOfAccount.objects.filter(account_type=6)
        self.fields['status'].widget = HiddenInput()
        self.fields['duty'].empty_label = None
        self.fields['duty'].queryset = Duty.objects.filter(date=duty.date)

rent_received/views.py
from django.shortcuts import render, get_object_or_404

from nps.custom_decorators.permission_required import permission_required
from .models import Rentreceived
from django.http import JsonResponse
from django.template.loader import render_to_string
from .forms import RentreceivedForm
from general_journal.models import GeneralJournal
from chart_of_accounts.models import ChartOfAccount


def rent_received_home(request):
    total_rent_received = Rentreceived.objects.count()
    return render(request, 'rent_receiveds/rent_received_home.html', {'total_rent_receiveds': total_rent_received})


@permission_required('rent_received.list_rentreceived')
def rent_received_list(request):
    rent_receiveds = Rentreceived.objects.all()
    total_rent_received = Rentreceived.objects.count()
    return render(request, 'rent_receiveds/rent_received_list.html', {'rent_receiveds': rent_receiveds,'total_rent_receiveds': total_rent_received})


def save_rent_received_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            rent_receiveds =  Rentreceived.objects.all()
            data['html_rent_received_list'] = render_to_string('rent_receiveds/includes/partial_rent_received_list.html', {
                'rent_receiveds': rent_receiveds
            })
            data['total_rent_receiveds'] = Rentreceived.objects.count()
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def update_rent_received_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            # general journal entry
            id = form.instance.id
            debit_acc = form.cleaned_data['bank'].id
            rent_amount = form.cleaned_data['rent_amount']
            duty = form.cleaned_data['duty']
            credit_acc = 40060001
            general_journal_1 = GeneralJournal(chartofaccount_id=debit_acc, duty_id=duty.id, voucher_type='RR',
                                               voucher_number=id, debit=rent_amount, credit=0,
                                               naration='To rent from company account ')
            general_journal_1.save()
            general_journal_2 = GeneralJournal(chartofaccount_id=credit_acc,  duty_id=duty.id, voucher_type='RR',
                                               voucher_number=id, debit=0, credit=rent_amount,
                                               naration='By bank account')
            general_journal_2.save()
            # general journal entry end
            rr = Rentreceived.objects.get(id=id)
            rr.status = 2
            rr.save()
            data['form_is_valid'] = True
            rent_receiveds =  Rentreceived.objects.all()
            data['html_rent_received_list'] = render_to_string('rent_receiveds/includes/partial_rent_received_list.html', {
                'rent_receiveds': rent_receiveds
            })
            data['total_rent_receiveds'] = Rentreceived.objects.count()
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


@permission_required('rent_received.add_rentreceived')
def rent_received_create(request):
    if request.method == 'POST':
        form = RentreceivedForm(request.POST)
    else:
        form = RentreceivedForm()
    return save_rent_received_form(request, form, 'rent_receiveds/includes/partial_rent_received_create.html')


@permission_required('rent_received.change_rentreceived')
def rent_received_update(request, pk):
    rent_received = get_object_or_404(Rentreceived, pk=pk)
    if request.method == 'POST':
        form = RentreceivedForm(request.POST, instance=rent_received)
    else:
        form = RentreceivedForm(instance=rent_received)
    return update_rent_received_form(request, form, 'rent_receiveds/includes/partial_rent_received_update.html')


@permission_required('rent_received.delete_rentreceived')
def rent_received_delete(request, pk):
    rent_received = get_object_or_404(Rentreceived, pk=pk)
    data = dict()
    if request.method == 'POST':
        rent_received.delete()
        GeneralJournal.objects.filter(voucher_number=pk, voucher_type='RR').delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        rent_receiveds = Rentreceived.objects.all()
        data['html_rent_received_list'] = render_to_string('rent_receiveds/includes/partial_rent_received_list.html', {
            'rent_receiveds': rent_receiveds
        })
        data['total_rent_receiveds'] = Rentreceived.objects.count()
    else:
        context = {'rent_received': rent_received}
        data['html_form'] = render_to_string('rent_receiveds/includes/partial_rent_received_delete.html',
                                             context,
                                             request=request,
                                             )
    return JsonResponse(data)

templates/rent_receiveds/includes/partial_rent_received_create.html
<form method="post" action="{% url 'rent_received_create' %}" class="js-rent_received-create-form">
  {% csrf_token %}
  <div class="modal-header bg-primary">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new rent received</h4>
  </div>
  <div class="modal-body">
  {% include 'rent_receiveds/includes/partial_rent_received_form.html' %}
  </div>
  <div class="modal-footer">
     <button type="button" class="btn btn-default" data-dismiss="modal"><i class="ace-icon fa fa-times white3"></i> Close</button>
        <button type="submit" class="btn btn-primary"><i class="ace-icon fa fa-floppy-o bigger-100"></i> Create rent received </button>
  </div>
</form>

templates/rent_receiveds/includes/partial_rent_received_delete.html
<form method="post" action="{% url 'rent_received_delete' rent_received.id %}" class="js-rent_received-delete-form">
  {% csrf_token %}
  <div class="modal-header" style="background-color: #D15B47;color: #fff;">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm rent received deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead"><i class="glyphicon glyphicon-alert"></i> Are you sure you want to delete the rent received <strong>{{ rent_received.title }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete rent received</button>
  </div>
</form>

templates/rent_receiveds/includes/partial_rent_received_form.html
{% load widget_tweaks %}

  {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}

templates/rent_receiveds/includes/partial_rent_received_list.html
{% for rent_received in rent_receiveds %}
    <tr>
        <td></td>
        <td>{{ rent_received.rent_cheque_no }}</td>
        <td>{{ rent_received.rent_receiving_date }}</td>
        <td>{{ rent_received.get_rent_receiving_month_display }}</td>
        <td>{{ rent_received.rent_bank_deposition_date }}</td>
        <td>{{ rent_received.bank }}</td>
        <td>{{ rent_received.rent_amount }}</td>
        {% if rent_received.status == 1 %}
            <td style="color:red;font-weight: bold;">{{ rent_received.get_status_display }} <span
                    class="glyphicon glyphicon-time"></span></td>
        {% else %}
            <td style="color: green;font-weight: bold;">{{ rent_received.get_status_display }} <span
                    class="glyphicon glyphicon-ok"></span></td>
        {% endif %}
        <td>
            {% if rent_received.status == 1 %}
                <button type="button"
                        class="btn btn-warning btn-sm js-update-rent_received"
                        data-url="{% url 'rent_received_update' rent_received.id %}">
                    <span class="glyphicon glyphicon-pencil"></span> Post
                </button>
                <button type="button"
                        class="btn btn-danger btn-sm js-delete-rent_received"
                        data-url="{% url 'rent_received_delete' rent_received.id %}">
                    <span class="glyphicon glyphicon-trash"></span> Delete
                </button>
            {% endif %}
        </td>
    </tr>
{% empty %}
    <tr>
        <td colspan="9" class="text-center bg-warning">No rent received</td>
    </tr>
{% endfor %}

templates/rent_receiveds/includes/partial_rent_received_update.html
{% load widget_tweaks %}

<form method="post" action="{% url 'rent_received_update' form.instance.pk %}" class="js-rent_received-update-form">
  {% csrf_token %}
  <div class="modal-header bg-primary">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Post rent received</h4>
  </div>
  <div class="modal-body">
    {% include 'rent_receiveds/includes/partial_rent_received_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="ace-icon fa fa-times white3"></i> Close</button>
         {% if form.status.value == 1 %}
            <button type='submit' class="btn btn-warning"><i
                    class="ace-icon fa fa-floppy-o bigger-100"></i> post it
            </button>
        {% endif %}
  </div>
</form>