cash/urls.py
from django.urls import path
from .views import CreditSaleList, CreditSaleUpdate, \
    LatestCash_outDelete, LatestCreditSaleCreate, CreditSaleDelete, \
    LatestCreditSaleUpdate, CreditSaleDetail, CreditSaleCreate, supplier_payment_list, \
    supplier_payment_home, supplier_payment_create, \
    supplier_payment_update, supplier_payment_delete, bank_deposition_list, bank_deposition_home, \
    bank_deposition_create, bank_deposition_update, bank_deposition_delete, \
    fuel_vehicle_income_list, fuel_vehicle_income_create, fuel_vehicle_income_update, fuel_vehicle_income_delete, \
    fuel_vehicle_income_home, GetDiscount, GetPrice, NetSaleList, NetSaleCreate, NetSaleDetail, NetSaleUpdate, \
    LatestNetSaleUpdate, NetSaleDelete, LatestNetSaleCreate, LatestNetSaleDelete, RecoveryList, RecoveryCreate, \
    RecoveryDetail, RecoveryUpdate, LatestRecoveryUpdate, RecoveryDelete, LatestRecoveryCreate, LatestRecoveryDelete

urlpatterns = [

    path('cash_in', NetSaleList.as_view(), name='cash_in_list'),
    path('cash_in/create', NetSaleCreate.as_view(), name='cash_in_create'),
    path('cash_in/<int:pk>/detail', NetSaleDetail.as_view(), name="cash_in_detail"),
    path('cash_in/<int:pk>/update', NetSaleUpdate.as_view(), name="cash_in_update"),
    path('cash_in/latest/<int:pk>/update', LatestNetSaleUpdate.as_view(), name="latest_cash_in_update"),
    path('cash_in/<int:pk>/delete', NetSaleDelete, name="cash_in_delete"),
    path('cash_in/latest/create', LatestNetSaleCreate, name="latest_cash_in_create"),
    path('cash_in/<int:pk>/latest/delete', LatestNetSaleDelete.as_view(), name="latest_cash_in_delete"),

    path('recovery', RecoveryList.as_view(), name='recovery_list'),
    path('recovery/create', RecoveryCreate.as_view(), name='recovery_create'),
    path('recovery/<int:pk>/detail', RecoveryDetail.as_view(), name="recovery_detail"),
    path('recovery/<int:pk>/update', RecoveryUpdate.as_view(), name="recovery_update"),
    path('recovery/latest/<int:pk>/update', LatestRecoveryUpdate.as_view(), name="latest_recovery_update"),
    path('recovery/<int:pk>/delete', RecoveryDelete, name="recovery_delete"),
    path('recovery/latest/create', LatestRecoveryCreate, name="latest_recovery_create"),
    path('recovery/<int:pk>/latest/delete', LatestRecoveryDelete.as_view(), name="latest_recovery_delete"),

    path('cash_out', CreditSaleList.as_view(), name='cash_out_list'),
    path('cash_out/create', CreditSaleCreate.as_view(), name='cash_out_create'),
    path('cash_out/<int:pk>/detail', CreditSaleDetail.as_view(), name="cash_out_detail"),
    path('cash_out/<int:pk>/update', CreditSaleUpdate.as_view(), name="cash_out_update"),
    path('cash_out/latest/<int:pk>/update', LatestCreditSaleUpdate.as_view(), name="latest_cash_out_update"),
    path('cash_out/<int:pk>/delete', CreditSaleDelete, name="cash_out_delete"),
    path('cash_out/latest/create', LatestCreditSaleCreate, name="latest_cash_out_create"),
    path('cash_out/<int:pk>/latest/delete', LatestCash_outDelete.as_view(), name="latest_cash_out_delete"),
    path('cash_out/get_discount', GetDiscount.as_view(), name="get_discount"),
    path('cash_out/get_price', GetPrice.as_view(), name="get_price"),

    path('supplier_payment/', supplier_payment_list, name='supplier_payment_list'),
    path('supplier_payment/home', supplier_payment_home, name='supplier_payment_home'),
    path('supplier_payment/create', supplier_payment_create, name='supplier_payment_create'),
    path('supplier_payment/<int:pk>/update', supplier_payment_update, name='supplier_payment_update'),
    path('supplier_payment/<int:pk>/delete', supplier_payment_delete, name='supplier_payment_delete'),

    path('bank_deposition/', bank_deposition_list, name='bank_deposition_list'),
    path('bank_deposition/home', bank_deposition_home, name='bank_deposition_home'),
    path('bank_deposition/create', bank_deposition_create, name='bank_deposition_create'),
    path('bank_deposition/<int:pk>/update', bank_deposition_update, name='bank_deposition_update'),
    path('bank_deposition/<int:pk>/delete', bank_deposition_delete, name='bank_deposition_delete'),

    path('fuel_vehicle_income/', fuel_vehicle_income_list, name='fuel_vehicle_income_list'),
    path('fuel_vehicle_income/create', fuel_vehicle_income_create, name='fuel_vehicle_income_create'),
    path('fuel_vehicle_income/home', fuel_vehicle_income_home, name='fuel_vehicle_income_home'),
    path('fuel_vehicle_income/<int:pk>/update', fuel_vehicle_income_update, name='fuel_vehicle_income_update'),
    path('fuel_vehicle_income/<int:pk>/delete', fuel_vehicle_income_delete, name='fuel_vehicle_income_delete'),

]

nps/urls.py
from allauth.account.views import LoginView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from accounts.views import login_after_password_change, privileges_required
from nps.views import login_success

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/password/change/', login_after_password_change, name='account_change_password'),
    path('privileges_required/', privileges_required, name="privileges_required"),
    path('accounts/', include('allauth.urls')),
    path('', include('dashboard.urls')),
    path('', include('products.urls')),
    path('', include('purchases.urls')),
    # path('', include('tanks.urls')),
    # path('', include('vehicles.urls')),
    path('', include('meters.urls')),
    path('', include('rent_received.urls')),
    path('', include('chart_of_accounts.urls')),
    path('', include('tank_lorries.urls')),
    path('', include('duties.urls')),
    path('', include('sales.urls')),
    path('', include('cash.urls')),
    path('', include('reports.urls')),
    # path('', include('customers.urls')),
    path('', include('expenses.urls')),
    path('', include('taxes.urls')),
    path('', include('discounts.urls')),
    path('', include('customer_limits.urls')),
    path('', include('bank_to_bank_transfer.urls')),
    path('', include('drawing.urls')),
    path('', include('bank_expense.urls')),
    path('', include('milli_short_recovery.urls')),
    path('', include('lorry_stock.urls')),
    path('login_success/', login_success, name='login_success'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cash/models.py
from django.db import models
from decimal import Decimal
from django.conf import settings
from chart_of_accounts.models import ChartOfAccount
from duties.models import DutyMen, Duty
from django.utils import timezone

from nps.models import ModelWithTimeStamp
from products.models import Product
from .choices import *


class NetSalem(ModelWithTimeStamp):
    STATUS = (
        (1, 'not posted'),
        (2, 'posted')
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    duty_person = models.ForeignKey(DutyMen, on_delete=models.CASCADE, null=False, blank=False)
    duty = models.ForeignKey(Duty, on_delete=models.CASCADE, null=True, blank=True)
    net_amount = models.DecimalField(max_digits=20, decimal_places=3, null=False, blank=False, default=Decimal('0.000'), verbose_name='Net amount')
    net_discount_amount = models.DecimalField(max_digits=20, decimal_places=3, null=False, blank=False,default=Decimal('0.000'), verbose_name='Net discount amount')
    status = models.SmallIntegerField(verbose_name='Status', choices=STATUS, default=1, null=True, blank=True)

    class Meta:
        permissions = (('list_netsalem', 'Can list netsalem'),)


class NetSales(ModelWithTimeStamp):
    netsalem = models.ForeignKey(NetSalem, on_delete=models.CASCADE, null=True, blank=True)
    account = models.ForeignKey(ChartOfAccount, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Account')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True, default=None,verbose_name='Product')
    qty_sold = models.DecimalField(max_digits=10, decimal_places=3, null=False, blank=False, verbose_name='Qty sold', default=Decimal('0.000'))
    price = models.DecimalField(max_digits=10, decimal_places=3, null=False, blank=False, default=Decimal('0.000'),verbose_name='Price / litre')
    nozzle_rate_amount = models.DecimalField(max_digits=20, decimal_places=3, null=False, blank=False,default=Decimal('0.000'), verbose_name='Nozzle/Amount')
    discount = models.DecimalField(max_digits=8, decimal_places=3, null=False, blank=False, default=Decimal('0.000'), verbose_name='Discount/L')
    discount_amount = models.DecimalField(max_digits=20, decimal_places=3, null=False, blank=False,default=Decimal('0.000'), verbose_name='Discount amount')
    amount = models.DecimalField(max_digits=20, decimal_places=3, null=False, blank=False, default=Decimal('0.000'), verbose_name='Amount')

    class Meta:
        default_permissions = ()
        # unique_together = ('account','product',)

    def __str__(self):
        return self.account


class Recoverym(ModelWithTimeStamp):
    STATUS = (
        (1, 'not posted'),
        (2, 'posted')
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    duty_person = models.ForeignKey(DutyMen, on_delete=models.CASCADE, null=False, blank=False)
    duty = models.ForeignKey(Duty, on_delete=models.CASCADE, null=True, blank=True)
    net_amount = models.DecimalField(max_digits=20, decimal_places=3, null=False, blank=False, default=Decimal('0.000'), verbose_name='Net amount')
    status = models.SmallIntegerField(verbose_name='Status', choices=STATUS, default=1, null=True, blank=True)

    class Meta:
        permissions = (('list_recoverym', 'Can list recoverym'),)


class Recoverys(ModelWithTimeStamp):
    recoverym = models.ForeignKey(Recoverym, on_delete=models.CASCADE, null=True, blank=True)
    account = models.ForeignKey(ChartOfAccount, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Account')
    amount = models.DecimalField(max_digits=20, decimal_places=3, null=False, blank=False, default=Decimal('0.000'), verbose_name='Amount')

    class Meta:
        default_permissions = ()
        # unique_together = ('account','product',)

    def __str__(self):
        return self.account


class CreditSalem(ModelWithTimeStamp):
    STATUS = (
        (1, 'not posted'),
        (2, 'posted')
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    duty_person = models.ForeignKey(DutyMen, on_delete=models.CASCADE, null=False, blank=False)
    duty = models.ForeignKey(Duty, on_delete=models.CASCADE, null=True, blank=True)
    net_amount = models.DecimalField(max_digits=20, decimal_places=3, null=False, blank=False, default=Decimal('0.000'), verbose_name='Net amount')
    net_discount_amount = models.DecimalField(max_digits=20, decimal_places=3, null=False, blank=False, default=Decimal('0.000'), verbose_name='Net discount amount')
    status = models.SmallIntegerField(verbose_name='Status', choices=STATUS, default=1, null=True, blank=True)
    class Meta:
        permissions = (('list_creditsalem', 'Can list creditsalem'),)

    def __str__(self):
        return "%s" % self.duty.date


class CreditSales(ModelWithTimeStamp):
    creditsalem = models.ForeignKey(CreditSalem, on_delete=models.CASCADE, null=True, blank=True)
    debit_account = models.ForeignKey(ChartOfAccount, on_delete=models.CASCADE, null=False, blank=True, verbose_name='Customer', related_name='debit_account')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True, default=None, verbose_name='Product')
    qty_sold = models.DecimalField(max_digits=10, decimal_places=3, null=False, blank=False, verbose_name='Qty sold', default=Decimal('0.000'))
    price = models.DecimalField(max_digits=10, decimal_places=3, null=False, blank=False, default=Decimal('0.000'),verbose_name='Price / litre')
    nozzle_rate_amount = models.DecimalField(max_digits=20, decimal_places=3, null=False, blank=False, default=Decimal('0.000'),verbose_name='Nozzle/Amount')
    discount = models.DecimalField(max_digits=8, decimal_places=3, null=False, blank=False, default=Decimal('0.000'),verbose_name='Discount/L')
    discount_amount = models.DecimalField(max_digits=20, decimal_places=3, null=False, blank=False, default=Decimal('0.000'), verbose_name='Discount amount')
    amount = models.DecimalField(max_digits=20, decimal_places=3, null=False, blank=False, default=Decimal('0.000'), verbose_name='Amount')

    class Meta:
        default_permissions = ()

    def __str__(self):
        return self.debit_account.account_name


class SupplierPayment(ModelWithTimeStamp):
    STATUS = (
        (1, 'not posted'),
        (2, 'posted')
    )
    supplier = models.ForeignKey(ChartOfAccount, on_delete=models.SET_NULL, null=True, related_name='sp_supplier')
    duty = models.ForeignKey(Duty, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Duty')
    bank = models.ForeignKey(ChartOfAccount, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='sp_bank')
    payment_for = models.ForeignKey(ChartOfAccount, on_delete=models.CASCADE, null=True, blank=True, default=None, verbose_name='Payment for')
    amount = models.DecimalField(max_digits=15, decimal_places=3, verbose_name='Amount')
    description = models.TextField(verbose_name='Description', null=True, blank=True, )
    cheque_no = models.CharField(max_length=20, verbose_name='Cheque #', null=True, blank=True)
    status = models.SmallIntegerField(verbose_name='', choices=STATUS, default=1, null=True, blank=True)

    class Meta:
        permissions = (('list_supplierpayment', 'Can list supplierpayment'),)


class BankDeposition(ModelWithTimeStamp):
    STATUS = (
        (1, 'not posted'),
        (2, 'posted')
    )

    DEPOSITION_FOR = (
        (1, 'Duty Cash'),
        (2, 'Recovery'),
        (3, 'Advance Received')
    )
    duty = models.ForeignKey(Duty, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Duty')
    bank = models.ForeignKey(ChartOfAccount, on_delete=models.CASCADE, null=False, blank=False, related_name='bd_bank')
    deposition_for = models.SmallIntegerField(verbose_name='Deposition for?', choices=DEPOSITION_FOR, default=1)
    amount = models.DecimalField(max_digits=15, decimal_places=3, verbose_name='Amount')
    description = models.TextField(verbose_name='Description', null=True, blank=True, )
    slip_no = models.CharField(max_length=20, verbose_name='Slip #', null=True, blank=True)
    status = models.SmallIntegerField(verbose_name='', choices=STATUS, default=1, null=True, blank=True)

    class Meta:
        permissions = (('list_bankdeposition', 'Can list bankdeposition'),)


class FuelVehicleIncome(ModelWithTimeStamp):
    duty = models.ForeignKey(Duty, on_delete=models.CASCADE, null=True, blank=True)
    vehicle = models.ForeignKey(ChartOfAccount, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='vehicle')
    amount = models.DecimalField(max_digits=15, decimal_places=3, verbose_name='Amount')

    class Meta:
        permissions = (('list_fuel_vehicle_income', 'Can list fuel_vehicle_income'),)

templates/cash/includes/cash_in_detail.html
{% extends '../../base.html' %}
{% load static %}
{% block page_css_files %}
    <link rel="stylesheet" href="{% static 'css/custom/custom.css' %}">
{% endblock %}
{% block style %}
    <style>

    </style>
{% endblock %}
<title>{% block title %}Detail cash in{% endblock %}</title>

{% block content %}
    <div class="main-content">
        <div class="main-content-inner">

            <div class="page-content">

                {% block page-header %}
                    <div class="col-md-12 bg-primary" style="padding: 8px;margin-bottom: 10px;font-size: 18px;">
                        Cash in ( Detail )
                    </div>
                {% endblock %}

                <div class="row" style="margin-bottom: 8px;">
                    <div class="col-md-6 col-lg-6 col-sm-6 col-xs-6">
                        <button type="button" class="btn btn-primary" onClick="javascript:history.go(-1);"><i
                                class="fa fa-chevron-left" aria-hidden="true"></i> back
                        </button>


                    </div>

                      <div class="col-md-6 col-lg-6 col-sm-6 col-xs-6 text-right">
                         <button type="button" id="btnPrint" name="addClient" value="Print"
                                class="btn btn-primary"><i class="fa fa-print" aria-hidden="true"></i>
                            print
                        </button>


                        <button type="button" id="generate_pdf" name="addClient" value="Print"
                                class="btn btn-primary" onclick="generatePDF();"><i
                                class="fa fa-file-pdf-o"
                                aria-hidden="true"></i> pdf
                        </button>
                    </div>
                </div>

                <div id="uniform_order_print">
                    <table class="table table-borderless">
                        <tbody>
                        <tr>
                            <td colspan="3">
                        <span class="bigger-120">
						<span class="blue bolder">Vista Filling Station (Cash in) </span>
					</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Duty person: {{ cash_in.duty_person }}</td>
                            <td>Duty date: {{ cash_in.duty }}</td>
                            <td>Duty date: {{ cash_in.date }}</td>
                        </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered" id="uniform_order-table_detail">
                        <thead>
                        <tr>
                            <th>Account</th>
                            <th colspan="2">Amount</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for uo in cash_in.netsales_set.all %}
                            <tr class="products_lists">
                                <td>{{ uo.account }}</td>
                                <td colspan="2">{{ uo.amount }}</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td  class="text-right">Sum:</td>
                            <td colspan="2">{{ cash_in.net_amount }}</td>
                        </tr>
                        </tbody>

                    </table>

                </div>
            </div>

        </div>
    </div>
    <!-- THE MODAL FOR SUB ACCOUNTS -->
    <div class="modal fade" id="modal-uniform_order">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
{% endblock %}
{#page specific js files#}
{% block custom_js_files %}

    <script src="{% static 'htmlTopdf/jspdf.min.js' %}"></script>
    <script src="{% static 'htmlTopdf/html2pdf.js' %}"></script>
    <script src="{% static 'htmlTopdf/html2canvas.min.js' %}"></script>
    <script src="{% static 'htmlTopdf/print2.min.js' %}"></script>


{% endblock %}

{#page specific inline js#}
{% block js_inline %}
    <script>
        function getDateTime() {
            var now = new Date();
            var year = now.getFullYear();
            var month = now.getMonth() + 1;
            var day = now.getDate();
            var hour = now.getHours();
            var minute = now.getMinutes();
            var second = now.getSeconds();
            if (month.toString().length == 1) {
                month = '0' + month;
            }
            if (day.toString().length == 1) {
                day = '0' + day;
            }
            if (hour.toString().length == 1) {
                hour = '0' + hour;
            }
            if (minute.toString().length == 1) {
                minute = '0' + minute;
            }
            if (second.toString().length == 1) {
                second = '0' + second;
            }
            var dateTime = day + '/' + month + '/' + year + ' ' + hour + ':' + minute + ':' + second;
            return dateTime;
        }

        {#pdf#}

        function generatePDF() {
            var element = document.getElementById('uniform_order_print');
            html2pdf(element, {
                margin: 1,
                filename: 'uniform_order-' + '{{uniform_order.id}}' + '-' + getDateTime() + '.pdf',
                image: {type: 'jpeg', quality: 1},
                html2canvas: {dpi: 600, letterRendering: true},
                jsPDF: {unit: 'in', format: 'letter', orientation: 'portrait'}
            });
        }

        {#print#}
        $(document).on('click', '#btnPrint', function () {
            $("#uniform_order_print").print({
                globalStyles: true,
                mediaPrint: false,
                stylesheet: null,
                noPrintSelector: ".no-print",
                iframe: true,
                append: null,
                prepend: null,
                manuallyCopyFormValues: true,
                deferred: $.Deferred(),
                timeout: 750,
                title: null,
                doctype: '<!doctype html>'
            });
        });

    </script>

{% endblock %}

templates/cash/includes/cash_out_detail.html
{% extends '../../base.html' %}
{% load static %}
{% block page_css_files %}
    <link rel="stylesheet" href="{% static 'css/custom/custom.css' %}">
{% endblock %}
{% block style %}
    <style>

    </style>
{% endblock %}
<title>{% block title %}Detail cash out{% endblock %}</title>

{% block content %}
    <div class="main-content">
        <div class="main-content-inner">

            <div class="page-content">

                {% block page-header %}
                    <div class="col-md-12 bg-primary" style="padding: 8px;margin-bottom: 10px;font-size: 18px;">
                        Cash out ( Detail )
                    </div>
                {% endblock %}

                <div class="row" style="margin-bottom: 8px;">
                    <div class="col-md-6 col-lg-6 col-sm-6 col-xs-6">

                        <button type="button" class="btn btn-primary" onClick="javascript:history.go(-1);"><i
                                class="fa fa-chevron-left" aria-hidden="true"></i> back
                        </button>

                    </div>
                    <div class="col-md-6 col-lg-6 col-sm-6 col-xs-6 text-right">
                        <button type="button" id="btnPrint" name="addClient" value="Print"
                                class="btn btn-primary"><i class="fa fa-print" aria-hidden="true"></i>
                            print
                        </button>


                        <button type="button" id="generate_pdf" name="addClient" value="Print"
                                class="btn btn-primary" onclick="generatePDF();"><i
                                class="fa fa-file-pdf-o"
                                aria-hidden="true"></i> pdf
                        </button>
                    </div>
                </div>

                <div id="uniform_order_print">
                    <table class="table table-borderless">
                        <tbody>
                        <tr>
                            <td colspan="3">
                        <span class="bigger-120">
						<span class="blue bolder">Vista Filling Station ( Cash out ) </span>
					</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Duty person: {{ cash_out.duty_person }}</td>
                            <td>Duty date: {{ cash_out.duty }}</td>
                            <td>Duty date: {{ cash_out.date }}</td>
                        </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered" id="uniform_order-table_detail">
                        <thead>
                        <tr>
                            <th>Debit account</th>
                            <th>Product</th>
                            <th>Amount</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for uo in cash_out.creditsales_set.all %}
                            <tr class="products_lists">
                                <td>{{ uo.debit_account }}</td>
                                <td>{{ uo.product }}</td>
                                <td colspan="2">{{ uo.amount }}</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td colspan="2" class="text-right">Sum:</td>
                            <td>{{ cash_out.net_amount }}</td>
                        </tr>
                        </tbody>

                    </table>

                </div>
            </div>

        </div>
    </div>
    <!-- THE MODAL FOR SUB ACCOUNTS -->
    <div class="modal fade" id="modal-uniform_order">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
{% endblock %}
{#page specific js files#}
{% block custom_js_files %}

    <script src="{% static 'htmlTopdf/jspdf.min.js' %}"></script>
    <script src="{% static 'htmlTopdf/html2pdf.js' %}"></script>
    <script src="{% static 'htmlTopdf/html2canvas.min.js' %}"></script>
    <script src="{% static 'htmlTopdf/print2.min.js' %}"></script>


{% endblock %}

{#page specific inline js#}
{% block js_inline %}
    <script>
        function getDateTime() {
            var now = new Date();
            var year = now.getFullYear();
            var month = now.getMonth() + 1;
            var day = now.getDate();
            var hour = now.getHours();
            var minute = now.getMinutes();
            var second = now.getSeconds();
            if (month.toString().length == 1) {
                month = '0' + month;
            }
            if (day.toString().length == 1) {
                day = '0' + day;
            }
            if (hour.toString().length == 1) {
                hour = '0' + hour;
            }
            if (minute.toString().length == 1) {
                minute = '0' + minute;
            }
            if (second.toString().length == 1) {
                second = '0' + second;
            }
            var dateTime = day + '/' + month + '/' + year + ' ' + hour + ':' + minute + ':' + second;
            return dateTime;
        }

        {#pdf#}

        function generatePDF() {
            var element = document.getElementById('uniform_order_print');
            html2pdf(element, {
                margin: 1,
                filename: 'uniform_order-' + '{{uniform_order.id}}' + '-' + getDateTime() + '.pdf',
                image: {type: 'jpeg', quality: 1},
                html2canvas: {dpi: 600, letterRendering: true},
                jsPDF: {unit: 'in', format: 'letter', orientation: 'portrait'}
            });
        }

        {#print#}
        $(document).on('click', '#btnPrint', function () {
            $("#uniform_order_print").print({
                globalStyles: true,
                mediaPrint: false,
                stylesheet: null,
                noPrintSelector: ".no-print",
                iframe: true,
                append: null,
                prepend: null,
                manuallyCopyFormValues: true,
                deferred: $.Deferred(),
                timeout: 750,
                title: null,
                doctype: '<!doctype html>'
            });
        });

    </script>

{% endblock %}

templates/cash/includes/partial_bank_deposition_list.html
{% for bank_deposition in bank_depositions %}
    <tr>
          <td>{{ bank_deposition.duty }}</td>
        <td>{{ bank_deposition.bank }}</td>
        <td>{{ bank_deposition.amount }}</td>
        <td>{{ bank_deposition.get_deposition_for_display }}</td>
       {% if bank_deposition.status == 1 %}
            <td style="color:red;font-weight: bold;">{{ bank_deposition.get_status_display }} <span
                    class="glyphicon glyphicon-time"></span></td>
        {% else %}
            <td style="color: green;font-weight: bold;">{{ bank_deposition.get_status_display }} <span
                    class="glyphicon glyphicon-ok"></span></td>
        {% endif %}
        <td>
             {% if bank_deposition.status == 1 %}
            <button type="button"
                    class="btn btn-warning btn-sm js-update-bank_deposition"
                    data-url="{% url 'bank_deposition_update' bank_deposition.id %}">
                <span class="glyphicon glyphicon-pencil"></span> post it
            </button>

            <button type="button"
                    class="btn btn-danger btn-sm js-delete-bank_deposition"
                    data-url="{% url 'bank_deposition_delete' bank_deposition.id %}">
                <span class="glyphicon glyphicon-trash"></span> Delete
            </button>
            {% endif %}
        </td>
    </tr>
{% empty %}
    <tr>
        <td colspan="6" class="text-center bg-warning">No any bank deposition</td>
    </tr>
{% endfor %}