chart_of_accounts/urls.py
from django.urls import path
from .views import main_account_list, main_account_create, main_account_update, main_account_delete, sub_account_list, sub_account_create, sub_account_update, sub_account_delete, \
    chart_of_account_list, chart_of_account_create, chart_of_account_update, chart_of_account_delete

urlpatterns = [
    # main accounts
    path('main_accounts/', main_account_list, name='main_account_list'),
    path('main_accounts/create', main_account_create, name='main_account_create'),
    path('main_accounts/<int:pk>/update', main_account_update, name='main_account_update'),
    path('main_accounts/<int:pk>/delete', main_account_delete, name='main_account_delete'),
    # sub accounts
    path('sub_accounts/', sub_account_list, name='sub_account_list'),
    path('sub_accounts/create', sub_account_create, name='sub_account_create'),
    path('sub_accounts/<int:pk>/update', sub_account_update, name='sub_account_update'),
    path('sub_accounts/<int:pk>/delete', sub_account_delete, name='sub_account_delete'),
    # chart of  accounts
    path('chart_of_accounts/', chart_of_account_list, name='chart_of_account_list'),
    path('chart_of_accounts/create', chart_of_account_create, name='chart_of_account_create'),
    path('chart_of_accounts/<int:pk>/update', chart_of_account_update, name='chart_of_account_update'),
    path('chart_of_accounts/<int:pk>/delete', chart_of_account_delete, name='chart_of_account_delete'),
]

nps/urls.py
from allauth.account.views import LoginView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from accounts.views import login_after_password_change, privileges_required
from nps.views import login_success

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/password/change/', login_after_password_change, name='account_change_password'),
    path('privileges_required/', privileges_required, name="privileges_required"),
    path('accounts/', include('allauth.urls')),
    path('', include('dashboard.urls')),
    path('', include('products.urls')),
    path('', include('purchases.urls')),
    # path('', include('tanks.urls')),
    # path('', include('vehicles.urls')),
    path('', include('meters.urls')),
    path('', include('rent_received.urls')),
    path('', include('chart_of_accounts.urls')),
    path('', include('tank_lorries.urls')),
    path('', include('duties.urls')),
    path('', include('sales.urls')),
    path('', include('cash.urls')),
    path('', include('reports.urls')),
    # path('', include('customers.urls')),
    path('', include('expenses.urls')),
    path('', include('taxes.urls')),
    path('', include('discounts.urls')),
    path('', include('customer_limits.urls')),
    path('', include('bank_to_bank_transfer.urls')),
    path('', include('drawing.urls')),
    path('', include('bank_expense.urls')),
    path('', include('milli_short_recovery.urls')),
    path('', include('lorry_stock.urls')),
    path('login_success/', login_success, name='login_success'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chart_of_accounts/models.py
from decimal import Decimal

from django.conf import settings
from django.db import models

from nps.models import ModelWithTimeStamp
from products.models import Product
from .choices import *


class MainAccount(models.Model):
    main_account_name = models.SmallIntegerField(verbose_name='Main account name', choices=main_accouts, unique=True)

    def __str__(self):
        return self.get_main_account_name_display()


class SubAccount(models.Model):
    mainaccount = models.ForeignKey(MainAccount, on_delete=models.CASCADE, verbose_name='Main account', null=True,
                                    blank=True, default=None)
    sub_account_name = models.SmallIntegerField(verbose_name='Sub account name', choices=sub_accounts, unique=True)

    def __str__(self):
        return str(self.get_sub_account_name_display())


class ChartOfAccount(ModelWithTimeStamp):
    SUPPLIER = 1
    PERSONAL = 2
    PRODUCT = 3
    REAL = 4
    EMPLOYEE = 5
    BANK = 6
    AGENCY_CUSTOMER = 7
    FUEL_PRODUCT = 8
    EXPENSE = 9
    COUNTER_SALES = 10
    LUBES_PURCHASES = 11
    LUBES_SALES = 12
    UNIFORM_PURCHASES = 13
    INCOME = 14
    VEHICLE = 15
    CLUB_CARD_CUSTOMER = 16
    CASH = 17
    OWNER = 18

    AC_TYPE = (
        ('', 'Select account type'),
        (SUPPLIER, 'Supplier'),
        (PERSONAL, 'Personal'),
        (EMPLOYEE, 'Employee'),
        (BANK, 'Bank'),
        (PRODUCT, 'Product'),
        (AGENCY_CUSTOMER, 'Agency customer'),
        (FUEL_PRODUCT, 'Fuel'),
        (REAL, 'Real'),
        (EXPENSE, 'Expense'),
        (COUNTER_SALES, 'Counter Sales'),
        (LUBES_PURCHASES, 'Lubes purchases'),
        (LUBES_SALES, 'Lubes sales'),
        (UNIFORM_PURCHASES, 'Uniform purchases'),
        (INCOME, 'Income'),
        (VEHICLE, 'Vehicle'),
        (CLUB_CARD_CUSTOMER, 'Club card customer'),
        (CASH, 'Cash'),
        (OWNER, 'Owner'),

    )

    BY_CARD_PAYER = 1
    CARD_DEPOSITOR = 2
    BY_BANK_PAYER = 3
    HYBRID = 4

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Product',null=True, blank=True, default=None)
    account_type = models.SmallIntegerField(choices=AC_TYPE, null=True, blank=True, verbose_name="Account type")
    subaccount = models.ForeignKey(SubAccount, on_delete=models.CASCADE, verbose_name='Sub account', null=True)
    account_name = models.CharField(max_length=70, verbose_name='Account name', unique=True)
    address = models.TextField(verbose_name='Address', null=True, blank=True)
    phone_number = models.CharField(max_length=15, verbose_name='Phone number', null=True, blank=True)
    is_account_active = models.BooleanField(verbose_name='is account active?', choices=is_account_active, default=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, default=None)

    def __str__(self):
        return self.account_name

chart_of_accounts/forms.py
from django import forms
from .models import MainAccount, SubAccount, ChartOfAccount
from django.utils.safestring import mark_safe


class MainAccountForm(forms.ModelForm):
    class Meta:
        model = MainAccount
        fields = '__all__'


class SubAccountForm(forms.ModelForm):
    class Meta:
        model = SubAccount
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SubAccountForm, self).__init__(*args, **kwargs)
        self.fields['mainaccount'].empty_label = 'Select a main account'


class ChartOfAccountForm(forms.ModelForm):
    class Meta:
        model = ChartOfAccount
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ChartOfAccountForm, self).__init__(*args, **kwargs)
        self.fields['subaccount'].empty_label = 'Select a sub account'
        self.fields['address'].widget.attrs['rows'] = 3

chart_of_accounts/views.py
from django.shortcuts import render, get_object_or_404

from nps.custom_decorators.permission_required import permission_required
from .models import MainAccount, SubAccount, ChartOfAccount
from django.http import JsonResponse
from django.template.loader import render_to_string
from .forms import MainAccountForm, SubAccountForm, ChartOfAccountForm
from django.db.models import Max


# main accounts


def main_account_list(request):
    main_accounts = MainAccount.objects.all()
    sub_accounts = SubAccount.objects.all()
    return render(request, 'chart_of_accounts/main_account_list.html',
                  {'main_accounts': main_accounts, 'sub_accounts': sub_accounts})


def save_main_account_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            main_accounts = MainAccount.objects.all()
            data['html_main_account_list'] = render_to_string(
                'chart_of_accounts/includes/partial_main_account_list.html', {
                    'main_accounts': main_accounts
                })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


@permission_required('chart_of_accounts.add_mainaccount')
def main_account_create(request):
    if request.method == 'POST':
        form = MainAccountForm(request.POST)
    else:
        form = MainAccountForm()
    return save_main_account_form(request, form, 'chart_of_accounts/includes/partial_main_account_create.html')


def main_account_update(request, pk):
    main_account = get_object_or_404(MainAccount, pk=pk)
    if request.method == 'POST':
        form = MainAccountForm(request.POST, instance=main_account)
    else:
        form = MainAccountForm(instance=main_account)
    return save_main_account_form(request, form, 'chart_of_accounts/includes/partial_main_account_update.html')


def main_account_delete(request, pk):
    main_account = get_object_or_404(MainAccount, pk=pk)
    data = dict()
    if request.method == 'POST':
        main_account.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        main_accounts = MainAccount.objects.all()
        data['html_main_account_list'] = render_to_string('chart_of_accounts/includes/partial_main_account_list.html', {
            'main_accounts': main_accounts
        })
    else:
        context = {'main_account': main_account}
        data['html_form'] = render_to_string('chart_of_accounts/includes/partial_main_account_delete.html',
                                             context,
                                             request=request,
                                             )
    return JsonResponse(data)


# sub account


def sub_account_list(request):
    sub_accounts = SubAccount.objects.all()
    return render(request, 'chart_of_accounts/main_account_list.html', {'sub_accounts': sub_accounts})


def save_sub_account_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            sub_account_name = form.cleaned_data['sub_account_name']
            main_account = form.cleaned_data['mainaccount'].id
            if int(str(sub_account_name)[:1]) != main_account:
                form.add_error('sub_account_name', 'This sub account is not related to selected main account!')
                data['form_is_valid'] = False
            else:
                subaccount = SubAccount(id=sub_account_name, mainaccount_id=main_account,
                                        sub_account_name=sub_account_name)
                subaccount.save()
                data['form_is_valid'] = True
            sub_accounts = SubAccount.objects.all()
            data['html_sub_account_list'] = render_to_string('chart_of_accounts/includes/partial_sub_account_list.html',
                                                             {
                                                                 'sub_accounts': sub_accounts
                                                             })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


@permission_required('chart_of_accounts.add_subaccount')
def sub_account_create(request):
    if request.method == 'POST':
        form = SubAccountForm(request.POST)
    else:
        form = SubAccountForm()
    return save_sub_account_form(request, form, 'chart_of_accounts/includes/partial_sub_account_create.html')

@permission_required('chart_of_accounts.change_subaccount')
def sub_account_update(request, pk):
    sub_account = get_object_or_404(SubAccount, pk=pk)
    if request.method == 'POST':
        form = SubAccountForm(request.POST, instance=sub_account)
    else:
        form = SubAccountForm(instance=sub_account)
    return save_sub_account_form(request, form, 'chart_of_accounts/includes/partial_sub_account_update.html')


@permission_required('chart_of_accounts.delete_mainaccount')
def sub_account_delete(request, pk):
    sub_account = get_object_or_404(SubAccount, pk=pk)
    data = dict()
    if request.method == 'POST':
        sub_account.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        sub_account = SubAccount.objects.all()
        data['html_sub_account_list'] = render_to_string('chart_of_accounts/includes/partial_sub_account_list.html', {
            'sub_accounts': sub_account
        })
    else:
        context = {'sub_account': sub_account}
        data['html_form'] = render_to_string('chart_of_accounts/includes/partial_sub_account_delete.html',
                                             context,
                                             request=request,
                                             )
    return JsonResponse(data)


# chart of accounts


def chart_of_account_list(request):
    #
    # if request.method == 'GET':
    #     q = request.GET.get('q',None)
    #     if q is not None:
    #         search = ChartOfAccount.objects.filter(account_type=q)
    #         if search:
    #             context = {'search': search}
    #             return render(request, 'chart_of_accounts/chart_of_account_list.html', {'search': search})
    #     else:
    #         search = ChartOfAccount.objects.all()
    #         return render(request, 'chart_of_accounts/chart_of_account_list.html', {'search': search})
    #
    # else:
    #     search = ChartOfAccount.objects.all()
    #     return render(request, 'chart_of_accounts/chart_of_account_list.html', {'search': search})

    chart_of_accounts = ChartOfAccount.objects.all()
    return render(request, 'chart_of_accounts/chart_of_account_list.html', {'chart_of_accounts': chart_of_accounts})


def save_chart_of_account_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():

            sub_account_name = form.cleaned_data['subaccount'].id
            account_name = form.cleaned_data['account_name']
            address = form.cleaned_data['address']
            phone_number = form.cleaned_data['phone_number']
            is_account_active = form.cleaned_data['is_account_active']
            account_type = form.cleaned_data['account_type']
            chart_of_account_max_id = ChartOfAccount.objects.filter(id__startswith=sub_account_name).aggregate(
                Max('id'))

            if chart_of_account_max_id['id__max'] is not None:
                data['form_is_valid'] = True
                chart_of_account_obj = ChartOfAccount(id=chart_of_account_max_id['id__max'] + 1,
                                                      subaccount_id=sub_account_name,
                                                      account_name=account_name,
                                                      address=address, phone_number=phone_number,
                                                      is_account_active=is_account_active, account_type=account_type)
                chart_of_account_obj.save()
            else:
                data['form_is_valid'] = True
                new_id = sub_account_name * 10000 + 1
                chart_of_account_obj = ChartOfAccount(id=new_id, subaccount_id=sub_account_name,
                                                      account_name=account_name,
                                                      address=address, phone_number=phone_number,
                                                      is_account_active=is_account_active, account_type=account_type)
                chart_of_account_obj.save()

            chart_of_accounts = ChartOfAccount.objects.all()
            data['html_chart_of_account_list'] = render_to_string(
                'chart_of_accounts/includes/partial_chart_of_account_list.html',
                {'chart_of_accounts': chart_of_accounts})
    else:
        data['form_is_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def update_chart_of_account_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            chart_of_accounts = ChartOfAccount.objects.all()
            data['html_chart_of_account_list'] = render_to_string(
                'chart_of_accounts/includes/partial_chart_of_account_list.html', {
                    'chart_of_accounts': chart_of_accounts
                })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)

templates/chart_of_accounts/includes/partial_chart_of_account_create.html
{% load widget_tweaks %}

<form method="post" action="{% url 'chart_of_account_create' %}" class="js-chart_of_account-create-form">
  {% csrf_token %}
  <div class="modal-header bg-primary">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new account</h4>
  </div>
  <div class="modal-body">
  {% include 'chart_of_accounts/includes/partial_chart_of_account_form.html' %}
  </div>
  <div class="modal-footer">
     <button type="button" class="btn btn-default" data-dismiss="modal"><i class="ace-icon fa fa-times white3"></i> Close</button>
        <button type="submit" class="btn btn-primary"><i class="ace-icon fa fa-floppy-o bigger-100"></i> Create new account </button>
  </div>
</form>

templates/chart_of_accounts/includes/partial_chart_of_account_delete.html
<form method="post" action="{% url 'chart_of_account_delete' chart_of_account.id %}" class="js-chart_of_account-delete-form">
  {% csrf_token %}
  <div class="modal-header" style="background-color: #D15B47;color: #fff;">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm account deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the account <strong>{{ chart_of_account.account_name }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete account</button>
  </div>
</form>

templates/chart_of_accounts/includes/partial_chart_of_account_form.html
{% load widget_tweaks %}

  {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}

templates/chart_of_accounts/includes/partial_chart_of_account_list.html
{% for chart_of_account in chart_of_accounts %}
    <tr>
    <td>{{ forloop.counter }}</td>
        <td>{{ chart_of_account.id }}</td>
         <td>{{ chart_of_account.account_name }}</td>
        <td>{{ chart_of_account.subaccount}}</td>
        <td>{{ chart_of_account.get_account_type_display }}</td>
        <td>{{ chart_of_account.address }}</td>
        <td>{{ chart_of_account.phone_number }}</td>
        <td>{{ chart_of_account.user }}</td>
        <td>{{ chart_of_account.get_is_account_active_display }}</td>

        <td>

            <button type="button"
                    class="btn btn-warning btn-xs js-update-chart_of_account"
                    data-url="{% url 'chart_of_account_update' chart_of_account.id %}">
                <span class="glyphicon glyphicon-pencil"></span>
            </button>
            <button type="button"
                    class="btn btn-danger btn-xs js-delete-chart_of_account"
                    data-url="{% url 'chart_of_account_delete' chart_of_account.id %}">
                <span class="glyphicon glyphicon-trash"></span>
            </button>

        </td>
    </tr>
{% empty %}
    <tr>
        <td colspan="9" class="text-center bg-warning">No chart of account</td>
    </tr>
{% endfor %}

templates/chart_of_accounts/includes/partial_chart_of_account_update.html
{% load widget_tweaks %}

<form method="post" action="{% url 'chart_of_account_update' form.instance.pk %}" class="js-chart_of_account-update-form">
  {% csrf_token %}
  <div class="modal-header bg-primary">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update account</h4>
  </div>
  <div class="modal-body">
    {% include 'chart_of_accounts/includes/partial_chart_of_account_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="ace-icon fa fa-times white3"></i> Close</button>
        <button type="submit" class="btn btn-primary"><i class="ace-icon fa fa-floppy-o bigger-100"></i> Update account </button>
  </div>
</form>

templates/chart_of_accounts/includes/partial_main_account_create.html
{% load widget_tweaks %}

<form method="post" action="{% url 'main_account_create' %}" class="js-main_account-create-form " >
  {% csrf_token %}
  <div class="modal-header bg-primary">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new account</h4>
  </div>
  <div class="modal-body">
  {% include 'chart_of_accounts/includes/partial_main_account_form.html' %}
  </div>
  <div class="modal-footer">
     <button type="button" class="btn btn-default" data-dismiss="modal"><i class="ace-icon fa fa-times white3"></i> Close</button>
        <button type="submit" class="btn btn-primary"><i class="ace-icon fa fa-floppy-o bigger-100"></i> Create new account </button>
  </div>
</form>

templates/chart_of_accounts/includes/partial_main_account_delete.html
<form method="post" action="{% url 'main_account_delete' main_account.id %}" class="js-main_account-delete-form">
  {% csrf_token %}
  <div class="modal-header" style="background-color: #D15B47;color: #fff;">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm main account deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead"><i class="glyphicon glyphicon-alert"></i> Are you sure you want to delete the main account <strong>{{ main_account.name }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete main account</button>
  </div>
</form>

templates/chart_of_accounts/includes/partial_main_account_form.html
{% load widget_tweaks %}

  {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}

templates/chart_of_accounts/includes/partial_main_account_list.html
{% for main_account in main_accounts %}
    <tr>
    <td>{{ forloop.counter }}</td>
        <td>{{ main_account.id }}</td>
        <td>{{ main_account.get_main_account_name_display }}</td>

{#        <td>#}
{##}
{#            <button type="button"#}
{#                    class="btn btn-warning btn-sm js-update-main_account"#}
{#                    data-url="{% url 'main_account_update' main_account.id %}">#}
{#                <span class="glyphicon glyphicon-pencil"></span> Edit#}
{#            </button>#}
{#            <button type="button"#}
{#                    class="btn btn-danger btn-sm js-delete-main_account"#}
{#                    data-url="{% url 'main_account_delete' main_account.id %}">#}
{#                <span class="glyphicon glyphicon-trash"></span> Delete#}
{#            </button>#}
{##}
{#        </td>#}
    </tr>
{% empty %}
    <tr>
        <td colspan="3" class="text-center bg-warning">No chart of account</td>
    </tr>
{% endfor %}

templates/chart_of_accounts/includes/partial_sub_account_create.html
{% load widget_tweaks %}

<form method="post" action="{% url 'sub_account_create' %}" class="js-sub_account-create-form">
  {% csrf_token %}
  <div class="modal-header bg-primary">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new sub account</h4>
  </div>
  <div class="modal-body">
  {% include 'chart_of_accounts/includes/partial_sub_account_form.html' %}
  </div>
  <div class="modal-footer">
     <button type="button" class="btn btn-default" data-dismiss="modal"><i class="ace-icon fa fa-times white3"></i> Close</button>
        <button type="submit" class="btn btn-primary"><i class="ace-icon fa fa-floppy-o bigger-100"></i> Create new sub account </button>
  </div>
</form>

templates/chart_of_accounts/includes/partial_sub_account_delete.html
<form method="post" action="{% url 'sub_account_delete' sub_account.id %}" class="js-sub_account-delete-form">
  {% csrf_token %}
  <div class="modal-header" style="background-color: #D15B47;color: #fff;">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm sub account deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead"><i class="glyphicon glyphicon-alert"></i> Are you sure you want to delete the sub account <strong>{{ sub_account.account_name }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete sub account</button>
  </div>
</form>

templates/chart_of_accounts/includes/partial_sub_account_form.html
{% load widget_tweaks %}

  {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}

templates/chart_of_accounts/includes/partial_sub_account_list.html
{% for sub_account in sub_accounts %}
    <tr>
    <td>{{ forloop.counter }}</td>
        <td>{{ sub_account.id }}</td>
        <td>{{ sub_account.mainaccount }}</td>
        <td>{{ sub_account.get_sub_account_name_display }}</td>

        <td>

            <button type="button"
                    class="btn btn-warning btn-xs js-update-sub_account"
                    data-url="{% url 'sub_account_update' sub_account.id %}">
                <span class="glyphicon glyphicon-pencil"></span>
            </button>
            <button type="button"
                    class="btn btn-danger btn-xs js-delete-sub_account"
                    data-url="{% url 'sub_account_delete' sub_account.id %}">
                <span class="glyphicon glyphicon-trash"></span>
            </button>

        </td>
    </tr>
{% empty %}
    <tr>
        <td colspan="5" class="text-center bg-warning">No sub account</td>
    </tr>
{% endfor %}

templates/chart_of_accounts/includes/partial_sub_account_update.html
{% load widget_tweaks %}

<form method="post" action="{% url 'sub_account_update' form.instance.pk %}" class="js-sub_account-update-form">
  {% csrf_token %}
  <div class="modal-header bg-primary">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update sub account</h4>
  </div>
  <div class="modal-body">
    {% include 'chart_of_accounts/includes/partial_sub_account_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="ace-icon fa fa-times white3"></i> Close</button>
        <button type="submit" class="btn btn-primary"><i class="ace-icon fa fa-floppy-o bigger-100"></i> Update sub account </button>
  </div>
</form>